CREATE TYPE "public"."user_roles" AS ENUM('user', 'admin', 'super_admin');--> statement-breakpoint
CREATE TABLE "users" (
	"created_at" timestamp (0) DEFAULT now() NOT NULL,
	"email" varchar(255) NOT NULL,
	"first_name" varchar(225) NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"last_name" varchar(225) NOT NULL,
	"phone" varchar(255),
	"updated_at" timestamp (0) DEFAULT now() NOT NULL,
	"user_id" text NOT NULL,
	"user_role" "user_roles" DEFAULT 'user' NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_phone_unique" UNIQUE("phone"),
	CONSTRAINT "users_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "user_id_unique" ON "users" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "email_unique" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "phone_unique" ON "users" USING btree ("phone");--> statement-breakpoint
CREATE INDEX "role_unique" ON "users" USING btree ("user_role");--> statement-breakpoint
CREATE INDEX "user_name_index" ON "users" USING btree ("first_name","last_name");