services:
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    restart: always
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_CLIENT_EMAIL=${GCP_CLIENT_EMAIL}
      - GCP_PRIVATE_KEY=${GCP_PRIVATE_KEY}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GCS_VIDEO_PREFIX=${GCS_VIDEO_PREFIX}
    # networks:
    #   - app_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   app_network:
#     external: true
